# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'git-trends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for git-trends
  pod 'Alamofire', '5.1'

  target 'git-trendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'git-trendsUITests' do
    # Pods for testing
  end

end
